backend:
  name: git-gateway
  branch: main # Укажите вашу ветку

media_folder: "img/gaids" # Папка для изображений
public_folder: "/img/gaids"

collections:
  - name: "gaids"
    label: "Гайды"
    folder: "gaids" # Где будут храниться файлы
    create: true
    slug: "{{slug}}"
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { name: "category", label: "Категория", widget: "select", 
          options: ["Фотоаппараты", "Смартфоны", "Ноутбуки", "Автоэлектроника"] }
      - { name: "image", label: "Превью", widget: "image" }
      - { name: "time", label: "Время", widget: "number" }
      - { name: "difficulty", label: "Сложность", widget: "select", 
          options: ["Легко", "Средне", "Сложно"] }
      - { name: "content", label: "Контент", widget: "markdown" }
