collections:
  - name: "gaids"
    label: "Гайды"
    folder: "content/guides" # Путь латиницей
    identifier_field: "category_id" # Новое поле для машинного имени
    fields:
      - { name: "title", label: "Название", widget: "string" }
      - { 
          name: "category_id", 
          label: "Категория (системное имя)", 
          widget: "hidden", # Поле будет скрыто в UI
          default: "{{slug}}"
        }
      - { 
          name: "category", 
          label: "Категория", 
          widget: "select",
          options: [
            { label: "Телевизоры", value: "tv" },
            { label: "Фотоаппараты", value: "cameras" },
            { label: "Приставки", value: "consoles" },
            { label: "Ноутбуки", value: "laptops" },
            { label: "Смартфоны", value: "smartphones" },
            { label: "Мелкая техника", value: "small-appliances" },
            { label: "Бытовая техника", value: "large-appliances" },
            { label: "Авто-Электроника", value: "auto-electronics" }
          ]
        }
